interface CountryData {
  id: string;
  name: string;
  code: string;
}

const countryData: CountryData[] = [
  {id:"v2y8m4zhnjql074", name:"Solomon Islands", code:"sb"},
  {id:"l965mkyh56r1ge4", name:"British Virgin Islands", code:"vg"},
  {id:"gpxwrxlhe3ryk0j", name:"Guam", code:"gu"},
  {id:"jednm9whxnryox8", name:"Cayman Islands", code:"ky"},
  {id:"z318q66hgzqo9jd", name:"Bahamas", code:"bs"},
  {id:"e4wyrn4hvkq86pv", name:"Cameroon", code:"cm"},
  {id:"ngy0or5jh3qwzv3", name:"Germany", code:"de"},
  {id:"p4jwq2gh6ym0veo", name:"South Sudan", code:"ss"},
  {id:"j1l4rjnh12m7vx5", name:"Mexico", code:"mx"},
  {id:"9k82rekh34repzj", name:"Jamaica", code:"jm"},
  {id:"9k82rekh6lrepzj", name:"Anguilla", code:"ai"},
  {id:"p3glrw7h63qdyjv", name:"Brunei", code:"bn"},
  {id:"p4jwq2gh4pm0veo", name:"Bulgaria", code:"bg"},
  {id:"p3glrw7h0oqdyjv", name:"Comoros", code:"km"},
  {id:"jednm9whgoryox8", name:"Palestine", code:"ps"},
  {id:"9dn1m1gh1jmoepl", name:"Malawi", code:"mw"},
  {id:"gy0or5jhl3qwzv3", name:"Lithuania", code:"lt"},
  {id:"yl5ergphpzr8k0o", name:"Nicaragua", code:"ni"},
  {id:"9vjxm8ghx2r6odg", name:"Cuba", code:"cu"},
  {id:"l965mkyh42r1ge4", name:"Uruguay", code:"uy"},
  {id:"z8yomo4hkwq0j6l", name:"Japan", code:"jp"},
  {id:"4zp5rzghj2q82w1", name:"Turkey", code:"tr"},
  {id:"p3glrw7hloqdyjv", name:"Gabon", code:"ga"},
  {id:"4zp5rzgh15q82w1", name:"Botswana", code:"bw"},
  {id:"gx7lm7ph00m2wdk", name:"United Arab Emirates", code:"ae"},
  {id:"gpxwrxlh1pryk0j", name:"Georgia", code:"ge"},
  {id:"jednm9whk0ryox8", name:"Slovenia", code:"si"},
  {id:"v2y8m4zhjkql074", name:"China", code:"cn"},
  {id:"e4wyrn4h2eq86pv", name:"Saint Vincent and the Grenadines", code:"vc"},
  {id:"z318q66h08qo9jd", name:"Venezuela", code:"ve"},
  {id:"p3glrw7hwwqdyjv", name:"Iceland", code:"is"},
  {id:"j1l4rjnh62m7vx5", name:"Croatia", code:"hr"},
  {id:"9kdj2ryohoq1zpg", name:"Ukraine", code:"ua"},
  {id:"9vjxm8ghggr6odg", name:"North Macedonia", code:"mk"},
  {id:"l965mkyh72r1ge4", name:"Cyprus", code:"cy"},
  {id:"z8yomo4h02q0j6l", name:"Uzbekistan", code:"uz"},
  {id:"p4jwq2gh0gm0veo", name:"Curacao", code:"cw"},
  {id:"e4wyrn4h7kq86pv", name:"Guinea-Bissau", code:"gw"},
  {id:"9dn1m1ghojmoepl", name:"Mozambique", code:"mz"},
  {id:"kdj2ryoh2kq1zpg", name:"Ivory Coast", code:"ci"},
  {id:"v2y8m4zhgkql074", name:"Nigeria", code:"ng"},
  {id:"7jednm9wh0ryox8", name:"Sweden", code:"se"},
  {id:"9k82rekhnlrepzj", name:"Bermuda", code:"bm"},
  {id:"jednm9whz0ryox8", name:"Thailand", code:"th"},
  {id:"z318q66hkyqo9jd", name:"Philippines", code:"ph"},
  {id:"9vjxm8gh4gr6odg", name:"Latvia", code:"lv"},
  {id:"0l965mkyh2r1ge4", name:"Finland", code:"fi"},
  {id:"3yl5ergphjr8k0o", name:"Northern Ireland", code:"gb-nir"},
  {id:"z8yomo4h2wq0j6l", name:"Morocco", code:"ma"},
  {id:"9vjxm8gh3lr6odg", name:"East Timor", code:"tl"},
  {id:"kn54qllhejqvy9d", name:"Brazil", code:"br"},
  {id:"j1l4rjnhe9m7vx5", name:"Aruba", code:"aw"},
  {id:"8y39mp1hpxmojxg", name:"Cambodia", code:"kh"},
  {id:"gpxwrxlhgpryk0j", name:"Slovakia", code:"sk"},
  {id:"jednm9wheoryox8", name:"Guyana", code:"gy"},
  {id:"kjw2r09h18rz84o", name:"Benin", code:"bj"},
  {id:"vl7oqdeh4wr510j", name:"new Zealand", code:"nz"},
  {id:"jednm9whdoryox8", name:"Congo", code:"cg"},
  {id:"yvl7oqdehwr510j", name:"Poland", code:"pl"},
  {id:"z318q66hjyqo9jd", name:"Zimbabwe", code:"zw"},
  {id:"8y39mp1hk8mojxg", name:"Madagascar", code:"mg"},
  {id:"9dn1m1gh04moepl", name:"Monaco", code:"mc"},
  {id:"7p4jwq2ghpm0veo", name:"Belgium", code:"be"},
  {id:"56ypq3nh1wmd7oj", name:"Sri Lanka", code:"lk"},
  {id:"kn54qllhkzqvy9d", name:"Democratic Republic of the Congo", code:"cd"},
  {id:"gy0or5jh06qwzv3", name:"Gibraltar", code:"gi"},
  {id:"8y39mp1h3zmojxg", name:"Serbia", code:"rs"},
  {id:"yl5ergphvjr8k0o", name:"Vietnam", code:"vn"},
  {id:"l965mkyhz0r1ge4", name:"Mongolia", code:"mn"},
  {id:"kdj2ryohjoq1zpg", name:"South Africa", code:"za"},
  {id:"z8yomo4h52q0j6l", name:"Kyrgyzstan", code:"kg"},
  {id:"d23xmvkh9lqg8ny", name:"US Virgin Islands", code:"vi"},
  {id:"gy0or5jh69qwzv3", name:"Djibouti", code:"dj"},
  {id:"yl5ergph5zr8k0o", name:"North Korea", code:"kp"},
  {id:"vl7oqdeheyr510j", name:"Gambia", code:"gm"},
  {id:"gpxwrxlh73ryk0j", name:"Liberia", code:"lr"},
  {id:"kdj2ryoh42q1zpg", name:"Sao Tome and Principe", code:"st"},
  {id:"kn54qllh13qvy9d", name:"Montserrat", code:"ms"},
  {id:"56ypq3nhzxmd7oj", name:"Tunisia", code:"tn"},
  {id:"z8yomo4hz2q0j6l", name:"Zambia", code:"zm"},
  {id:"gy0or5jhj6qwzv3", name:"Suriname", code:"sr"},
  {id:"gy0or5jhj9qwzv3", name:"Tahiti", code:"pf"},
  {id:"4zp5rzgh4eq82w1", name:"Tonga", code:"to"},
  {id:"kn54qllhdzqvy9d", name:"Mauritania", code:"mr"},
  {id:"x4zp5rzgh2q82w1", name:"Scotland", code:"gb-sct"},
  {id:"p3glrw7hjwqdyjv", name:"Saudi Arabia", code:"sa"},
  {id:"gpxwrxlh2zryk0j", name:"Uganda", code:"ug"},
  {id:"l965mkyh16r1ge4", name:"Saint Lucia", code:"lc"},
  {id:"p3glrw7hooqdyjv", name:"Trinidad and Tobago", code:"tt"},
  {id:"4zp5rzgh25q82w1", name:"Guinea", code:"gn"},
  {id:"d23xmvkhoxqg8ny", name:"United States", code:"us"},
  {id:"j1l4rjnh39m7vx5", name:"Cape Verde", code:"cv"},
  {id:"0gx7lm7ph0m2wdk", name:"Spain", code:"es"},
  {id:"kjw2r09h9jrz84o", name:"Liechtenstein", code:"li"},
  {id:"d23xmvkh4pqg8ny", name:"Myanmar", code:"mm"},
  {id:"gpxwrxlhjpryk0j", name:"Algeria", code:"dz"},
  {id:"gx7lm7ph5nm2wdk", name:"Bangladesh", code:"bd"},
  {id:"gx7lm7phpnm2wdk", name:"Antigua and Barbuda", code:"ag"},
  {id:"z318q66h2zqo9jd", name:"Chad", code:"td"},
  {id:"9vjxm8gh9lr6odg", name:"New Caledonia", code:"nc"},
  {id:"gpxwrxlh7zryk0j", name:"Swaziland", code:"sz"},
  {id:"p4jwq2ghkpm0veo", name:"Paraguay", code:"py"},
  {id:"gy0or5jh43qwzv3", name:"Argentina", code:"ar"},
  {id:"gpxwrxlh9pryk0j", name:"Australia", code:"au"},
  {id:"z8yomo4hx9q0j6l", name:"American Samoa", code:"as"},
  {id:"4zp5rzghz2q82w1", name:"Qatar", code:"qa"},
  {id:"vl7oqdehdyr510j", name:"Tanzania", code:"tz"},
  {id:"e4wyrn4h85q86pv", name:"Bosnia and Herzegovina", code:"ba"},
  {id:"vl7oqdeh1yr510j", name:"Bhutan", code:"bt"},
  {id:"4zp5rzgh72q82w1", name:"Chile", code:"cl"},
  {id:"p4jwq2gh1gm0veo", name:"Togo", code:"tg"},
  {id:"v2y8m4zhx4ql074", name:"Cook Islands", code:"ck"},
  {id:"e4wyrn4he5q86pv", name:"Honduras", code:"hn"},
  {id:"yl5ergph3jr8k0o", name:"Canada", code:"ca"},
  {id:"kn54qllh2jqvy9d", name:"Wales", code:"gb-wls"},
  {id:"e4wyrn4hd5q86pv", name:"India", code:"in"},
  {id:"yl5ergphojr8k0o", name:"Estonia", code:"ee"},
  {id:"v2y8m4zh1jql074", name:"Mali", code:"ml"},
  {id:"9vjxm8gh92r6odg", name:"Afghanistan", code:"af"},
  {id:"8y39mp1h18mojxg", name:"Senegal", code:"sn"},
  {id:"l965mkyh32r1ge4", name:"Kuwait", code:"kw"},
  {id:"156ypq3nhxmd7oj", name:"Romania", code:"ro"},
  {id:"kdj2ryohdkq1zpg", name:"Laos", code:"la"},
  {id:"j1l4rjnh20m7vx5", name:"Vanuatu", code:"vu"},
  {id:"56ypq3nhgwmd7oj", name:"Equatorial Guinea", code:"gq"},
  {id:"j1l4rjnhk9m7vx5", name:"Kosovo", code:"xk"},
  {id:"gx7lm7phnnm2wdk", name:"Maldives", code:"mv"},
  {id:"yl5ergphyvr8k0o", name:"Puerto Rico", code:"pr"},
  {id:"p3glrw7hywqdyjv", name:"Egypt", code:"eg"},
  {id:"v2y8m4zh4jql074", name:"Lesotho", code:"ls"},
  {id:"d23xmvkhdxqg8ny", name:"Bahrain", code:"bh"},
  {id:"xkn54qllhjqvy9d", name:"France", code:"fr"},
  {id:"9dn1m1ghnxmoepl", name:"Iraq", code:"iq"},
  {id:"56ypq3nh4wmd7oj", name:"Haiti", code:"ht"},
  {id:"xe4wyrn4h5q86pv", name:"Ireland", code:"ie"},
  {id:"6j1l4rjnh2m7vx5", name:"Netherlands", code:"nl"},
  {id:"9k82rekh14repzj", name:"Panama", code:"pa"},
  {id:"dkjw2r09hvrz84o", name:"Russia", code:"ru"},
  {id:"gx7lm7ph8jm2wdk", name:"Samoa", code:"ws"},
  {id:"56ypq3nh5xmd7oj", name:"South Korea", code:"kr"},
  {id:"jednm9wh90ryox8", name:"Peru", code:"pe"},
  {id:"kz8yomo4hwq0j6l", name:"Greece", code:"gr"},
  {id:"8y39mp1h98mojxg", name:"Saint Kitts and Nevis", code:"kn"},
  {id:"kjw2r09hxvrz84o", name:"Indonesia", code:"id"},
  {id:"d23xmvkhgpqg8ny", name:"Burkina Faso", code:"bf"},
  {id:"e4wyrn4h9kq86pv", name:"Grenada", code:"gd"},
  {id:"z318q66ho8qo9jd", name:"Albania", code:"al"},
  {id:"gx7lm7pho0m2wdk", name:"Andorra", code:"ad"},
  {id:"4zp5rzgh0eq82w1", name:"Belize", code:"bz"},
  {id:"gx7lm7phk0m2wdk", name:"Belarus", code:"by"},
  {id:"yl5ergphnzr8k0o",name:"Ethiopia", code:"et"},
  {id:"56ypq3nheemd7oj",name:"Seychelles", code:"sc"},
  {id:"1v2y8m4zhkql074",name:"Czech Republic", code:"cz"},
  {id:"kp3glrw7hwqdyjv",name:"England", code:"gb-eng"},
  {id:"p4jwq2ghvpm0veo",name:"Jordan", code:"jo"},
  {id:"29dn1m1ghxmoepl",name:"Switzerland", code:"ch"},
  {id:"kn54qllh93qvy9d",name:"Barbados", code:"bb"},
  {id:"gy0or5jh16qwzv3",name:"Tajikistan", code:"tj"},
  {id:"9dn1m1gh74moepl",name:"Dominica", code:"dm"},
  {id:"z8yomo4h7wq0j6l",name:"Luxembourg", code:"lu"},
  {id:"kjw2r09hlvrz84o",name:"Moldova", code:"md"},
  {id:"vl7oqdehnwr510j",name:"Armenia", code:"am"},
  {id:"d23xmvkhxpqg8ny",name:"Namibia", code:"na"},
  {id:"9vjxm8gh8gr6odg",name:"Libya", code:"ly"},
  {id:"kdj2ryoh5kq1zpg",name:"Turkmenistan", code:"tm"},
  {id:"9vjxm8ghjgr6odg",name:"Iran", code:"ir"},
  {id:"9dn1m1ghexmoepl",name:"Bolivia", code:"bo"},
  {id:"kdj2ryohkoq1zpg",name:"Montenegro", code:"me"},
  {id:"kdj2ryohyoq1zpg",name:"El Salvador", code:"sv"},
  {id:"z8yomo4h92q0j6l",name:"Hong Kong, China", code:"hk"},
  {id:"v2y8m4zh3kql074",name:"Malta", code:"mt"},
  {id:"vl7oqdeh2lr510j",name:"Macao, China", code:"mo"},
  {id:"p3glrw7h03qdyjv",name:"Dominican Republic", code:"do"},
  {id:"jednm9wh6nryox8",name:"Papua New Guinea", code:"pg"},
  {id:"d9k82rekhgrepzj",name:"Denmark", code:"dk"},
  {id:"8y39mp1h5zmojxg",name:"Colombia", code:"co"},
  {id:"8y39mp1hwxmojxg",name:"Turks and Caicos Islands", code:"tc"},
  {id:"j1l4rjnhz2m7vx5",name:"Yemen", code:"ye"},
  {id:"l965mkyhg0r1ge4",name:"Niger", code:"ne"},
  {id:"xz318q66h8qo9jd",name:"Austria", code:"at"},
  {id:"9k82rekh84repzj",name:"Central African Republic", code:"cf"},
  {id:"28y39mp1hzmojxg",name:"Norway", code:"no"},
  {id:"j1l4rjnh50m7vx5",name:"Eritrea", code:"er"},
  {id:"gx7lm7phnjm2wdk",name:"Mauritius", code:"mu"},
  {id:"d23xmvkh3xqg8ny",name:"Hungary", code:"hu"},
  {id:"56ypq3nh0xmd7oj",name:"Faroe Islands", code:"fo"},
  {id:"kjw2r09hw8rz84o",name:"Rwanda", code:"rw"},
  {id:"8y39mp1hjzmojxg",name:"Oman", code:"om"},
  {id:"kdj2ryohnkq1zpg",name:"San Marino", code:"sm"},
  {id:"9d23xmvkhxqg8ny",name:"Portugal", code:"pt"},
  {id:"p4jwq2ghpym0veo",name:"Somalia", code:"so"},
  {id:"9vjxm8gh22r6odg",name:"Burundi", code:"bi"},
  {id:"9dn1m1gh4xmoepl",name:"Kazakhstan", code:"kz"},
  {id:"vl7oqdeh6wr510j",name:"Guatemala", code:"gt"},
  {id:"4zp5rzghp5q82w1",name:"Ghana", code:"gh"},
  {id:"9k82rekhvgrepzj",name:"Israel", code:"il"},
  {id:"49vjxm8ghgr6odg",name:"Italy", code:"it"},
  {id:"gpxwrxlhvzryk0j",name:"Fiji", code:"fj"},
  {id:"p3glrw7h1wqdyjv",name:"Azerbaijan", code:"az"},
  {id:"z318q66hv8qo9jd",name:"Lebanon", code:"lb"},
  {id:"kjw2r09hnvrz84o",name:"Costa Rica", code:"cr"},
  {id:"9k82rekh9grepzj",name:"Ecuador", code:"ec"},
  {id:"kjw2r09hp8rz84o",name:"Taipei, China", code:"tw"},
  {id:"gy0or5jhe3qwzv3",name:"Singapore", code:"sg"},
  {id:"l965mkyhn0r1ge4",name:"Pakistan", code:"pk"},
  {id:"d23xmvkhkpqg8ny",name:"Angola", code:"ao"},
  {id:"p4jwq2gh7gm0veo",name:"Syria", code:"sy"},
  {id:"d23xmvkhwlqg8ny",name:"Nepal", code:"np"},
  {id:"gx7lm7ph9nm2wdk",name:"Sudan", code:"sd"},
  {id:"z318q66h7yqo9jd",name:"Sierra Leone", code:"sl"},
  {id:"9dn1m1gh8jmoepl",name:"Kenya", code:"ke"},
  {id:"kn54qllhxjqvy9d",name:"Malaysia", code:"my"}
];

export const getCountryById = (id: string): Country | undefined => {
  const country = countryData.find(c => c.id === id);
  if (!country) return undefined;

  return {
    id: country.id,
    name: country.name,
    code: country.code,
    logo: `/img/flags/${country.code}.svg`
  };
};